/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CarProfile;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author agarw
 */
public class CreateCarProfile extends javax.swing.JFrame {

    /**
     * Creates new form CreateCarProfile
     */
    
    ArrayList<CarProfile> serviceRecords;
    CarProfile carProfile;
    String imagePath;
    public CreateCarProfile(CarProfile carProfile) {
        initComponents();
        serviceRecords = new ArrayList<CarProfile>();
        //populateArrayList();
        this.carProfile = carProfile;
       
    }

    public CreateCarProfile() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        brandNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        colorField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        engineNoField = new javax.swing.JTextField();
        seatsNumberField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        licensePlateField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        telephoneNumberField = new javax.swing.JTextField();
        emailAddressField = new javax.swing.JTextField();
        drivingLicenseField = new javax.swing.JTextField();
        ssnField = new javax.swing.JTextField();
        warrantyField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        serviceDate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        filePathField = new javax.swing.JTextField();
        photoField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Brand Name:");

        brandNameField.setForeground(new java.awt.Color(204, 0, 204));
        brandNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameFieldActionPerformed(evt);
            }
        });
        brandNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandNameFieldKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create a new car profile");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 255));
        jLabel3.setText("Model :");

        modelField.setForeground(new java.awt.Color(204, 0, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 255));
        jLabel4.setText("Engine No. :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 255));
        jLabel5.setText("Year :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 255));
        jLabel6.setText("Color :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 255));
        jLabel7.setText("Seats Number :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("    Car Details");

        colorField.setForeground(new java.awt.Color(204, 0, 204));

        yearField.setForeground(new java.awt.Color(204, 0, 204));
        yearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearFieldActionPerformed(evt);
            }
        });
        yearField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearFieldKeyTyped(evt);
            }
        });

        engineNoField.setForeground(new java.awt.Color(204, 0, 204));
        engineNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineNoFieldActionPerformed(evt);
            }
        });

        seatsNumberField.setForeground(new java.awt.Color(204, 0, 204));
        seatsNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsNumberFieldActionPerformed(evt);
            }
        });
        seatsNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seatsNumberFieldKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 255));
        jLabel9.setText("License Plates :");

        licensePlateField.setForeground(new java.awt.Color(204, 0, 204));
        licensePlateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licensePlateFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 153));
        jLabel10.setText("  Owner's Details");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 255));
        jLabel11.setText("Name :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 255));
        jLabel12.setText("Address :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 255));
        jLabel13.setText("Telephone Number :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 255));
        jLabel14.setText("Email address :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 51, 255));
        jLabel15.setText("Driving License :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 51, 255));
        jLabel16.setText("SSN :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 255));
        jLabel17.setText("Warranty Year :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 51, 255));
        jLabel18.setText("Photo :");

        nameField.setForeground(new java.awt.Color(204, 0, 204));
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
        });

        addressField.setForeground(new java.awt.Color(204, 0, 204));

        telephoneNumberField.setForeground(new java.awt.Color(204, 0, 204));
        telephoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNumberFieldActionPerformed(evt);
            }
        });
        telephoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneNumberFieldKeyPressed(evt);
            }
        });

        emailAddressField.setForeground(new java.awt.Color(204, 0, 204));

        drivingLicenseField.setForeground(new java.awt.Color(204, 0, 204));

        ssnField.setForeground(new java.awt.Color(204, 0, 204));
        ssnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnFieldActionPerformed(evt);
            }
        });

        warrantyField.setForeground(new java.awt.Color(204, 0, 204));
        warrantyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyFieldActionPerformed(evt);
            }
        });
        warrantyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                warrantyFieldKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 255));
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 255));
        jButton2.setText("Save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("  Service Records");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 51, 255));
        jLabel20.setText("Type of Service :");

        jComboBox1.setForeground(new java.awt.Color(204, 0, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interim Car Sevice", "Full Car Service", "Air filter change", "Fuel filter/ Spark plugs change", "Extensive brake inspection", "Wheel bearings and shock absorbers inspection", "Electrical components tested", "Air conditioning system inspection", "Radiator and coolant hose checked", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 51, 255));
        jLabel21.setText("Date of Service :");

        serviceDate.setForeground(new java.awt.Color(204, 0, 204));
        serviceDate.setToolTipText("mm/dd/yyyy");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 51, 255));
        jLabel22.setText("Charged Price :");

        price.setForeground(new java.awt.Color(204, 0, 204));
        price.setToolTipText("");

        filePathField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(engineNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(licensePlateField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telephoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(drivingLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(warrantyField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(serviceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1)
                            .addComponent(emailAddressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(ssnField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filePathField)
                            .addComponent(photoField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(brandNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(engineNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(seatsNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(licensePlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(telephoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(drivingLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(warrantyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(serviceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(photoField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void engineNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineNoFieldActionPerformed

    private void licensePlateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licensePlateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licensePlateFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser l_ImageChooser = new JFileChooser();
        //l_ImageChooser.showOpenDialog(null);
        // File f = l_ImageChooser.getSelectedFile();
        l_ImageChooser.setCurrentDirectory(new File("user.dir"));

        FileNameExtensionFilter imageExtensions = new FileNameExtensionFilter(" All Pic", "png", "jpeg","jpg","gif");
        l_ImageChooser.addChoosableFileFilter(imageExtensions);

        int a = l_ImageChooser.showSaveDialog(null);
        if(a == JFileChooser.APPROVE_OPTION)
        {
            File f = l_ImageChooser.getSelectedFile();
            imagePath = f.getAbsolutePath();
            filePathField.setText(imagePath);
            System.out.println("chosen image:"+imagePath);
            ImageIcon chosenImage = new ImageIcon(imagePath);
            Image l_image = chosenImage.getImage().getScaledInstance(photoField.getWidth(), photoField.getHeight(), Image.SCALE_SMOOTH);
            photoField.setIcon(new ImageIcon(l_image));
        //l_history.
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        boolean val = false; 
        if (brandNameField.getText().isEmpty() || modelField.getText().isEmpty() || colorField.getText().isEmpty()||
            yearField.getText().isEmpty() || engineNoField.getText().isEmpty() || seatsNumberField.getText().isEmpty() ||
            licensePlateField.getText().isEmpty() || nameField.getText().isEmpty() || addressField.getText().isEmpty() ||
            telephoneNumberField.getText().isEmpty() || emailAddressField.getText().isEmpty() || drivingLicenseField.getText().isEmpty() ||
            ssnField.getText().isEmpty() || warrantyField.getText().isEmpty() || filePathField.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please fill the empty fields!");
            val = true;
        }
        else {
            carProfile.setBrandNam(brandNameField.getText().trim());
            carProfile.setCarModel(modelField.getText().trim());
            carProfile.setColorOfCar(colorField.getText().trim());
            if (yearField.getText().length() == 4){
                carProfile.setPurchaseYear(Integer.parseInt(yearField.getText().trim()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter valid year!");
                val = true;
            }
            
            carProfile.setEngineNumber(engineNoField.getText().trim());
            carProfile.setSeatsNumber(Integer.parseInt(seatsNumberField.getText().trim()));
            carProfile.setLicensePlate(licensePlateField.getText().trim());
            carProfile.setOwnerName(nameField.getText().trim());
            carProfile.setAddress(addressField.getText().trim());
            if (telephoneNumberField.getText().length() == 10){
                carProfile.setOwnerTelephoneNumber(telephoneNumberField.getText());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter valid phone number!");
                val = true;
            }
            
            if (emailAddressField.getText().contains("@"))
            {
                carProfile.setOwnerEmailAddress(emailAddressField.getText().trim());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Plese enter valid Email Address!");
                val = true;
            }
            
            carProfile.setDrivingLicense(drivingLicenseField.getText().trim());
            carProfile.setOwnersSsn(ssnField.getText().trim());
            if (warrantyField.getText().length() == 4){
                carProfile.setWarrantyYear(Integer.parseInt(warrantyField.getText().trim()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter valid year!");
                val = true;
            }
            
//            carProfile.setTyprOfService((String)jComboBox1.getSelectedItem());
//            carProfile.setDateOfService(serviceDate.getText().trim());
//            carProfile.setChargedPrice(Double.parseDouble(price.getText().trim()));
            
            ArrayList<CarProfile> serviceRecords = new ArrayList<CarProfile>();
            serviceRecords.add(new CarProfile(jComboBox1.getSelectedItem().toString(), serviceDate.getText().trim(),
                    Double.parseDouble(price.getText().trim())));
            System.out.println("service value ==>" + jComboBox1.getSelectedItem().toString());
            carProfile.setServiceRecords(serviceRecords);
            carProfile.setPhoto(imagePath);
            
            val = false;
            if(!val){
                JOptionPane.showMessageDialog(null, "Data saved successfully!Your data has been saved");
                new CreateCarProfile().setVisible(false);
            }
            
//            CarProfile carProfile = new CarProfile(nameBrand, nameModel, typeColor, numberYear, numberSeats,
//                    numberEngine, platesLicense, nameOwner, addressEmail, numberTelephone, licenseDriving, socialSecurityNum, 
//                    addressOwner, yearWarranty, newImage , serviceType, dateService, priceCharged);
            
            //carProfiles.add(carProfile);
            
            //saveCarProfilestoFiles();
        
        
        
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void brandNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameFieldActionPerformed

    private void ssnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedValue = jComboBox1.getSelectedItem().toString();
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void brandNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandNameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameFieldKeyPressed

    private void yearFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFieldKeyTyped

    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed
        // TODO add your handling code here: 
        Character c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            nameField.setEditable(true);
        }
        else {
            nameField.setEditable(false);
        }
    }//GEN-LAST:event_nameFieldKeyPressed

    private void telephoneNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneNumberFieldKeyPressed
        // TODO add your handling code here:
        Character c =evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            telephoneNumberField.setEditable(true);
        }
        else
        {
            telephoneNumberField.setEditable(false);
        }
        
    }//GEN-LAST:event_telephoneNumberFieldKeyPressed

    private void telephoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNumberFieldActionPerformed

    private void yearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFieldActionPerformed

    private void warrantyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_warrantyFieldActionPerformed

    private void yearFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearFieldKeyPressed
        // TODO add your handling code here:
        Character c =evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            yearField.setEditable(true);
        }
        else
        {
            yearField.setEditable(false);
        }
    }//GEN-LAST:event_yearFieldKeyPressed

    private void warrantyFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_warrantyFieldKeyPressed
        // TODO add your handling code here:
        Character c =evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            warrantyField.setEditable(true);
        }
        else
        {
            warrantyField.setEditable(false);
        }
    }//GEN-LAST:event_warrantyFieldKeyPressed

    private void seatsNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsNumberFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_seatsNumberFieldActionPerformed

    private void seatsNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsNumberFieldKeyPressed
        // TODO add your handling code here:
        Character c =evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            seatsNumberField.setEditable(true);
        }
        else
        {
            seatsNumberField.setEditable(false);
        }
    }//GEN-LAST:event_seatsNumberFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCarProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCarProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCarProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCarProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCarProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField brandNameField;
    private javax.swing.JTextField colorField;
    private javax.swing.JTextField drivingLicenseField;
    private javax.swing.JTextField emailAddressField;
    private javax.swing.JTextField engineNoField;
    private javax.swing.JTextField filePathField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField licensePlateField;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel photoField;
    private javax.swing.JTextField price;
    private javax.swing.JTextField seatsNumberField;
    private javax.swing.JTextField serviceDate;
    private javax.swing.JTextField ssnField;
    private javax.swing.JTextField telephoneNumberField;
    private javax.swing.JTextField warrantyField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
byte[] photo = null;
String fileName = null;
BufferedImage newImage = null;

//    private void populateArrayList() {
//        try
//        {
//            FileInputStream file = new FileInputStream("CarProfiles.dat");
//            ObjectInputStream inputFile = new ObjectInputStream(file);
//            boolean endOfFile = false;
//            
//            while(!endOfFile)
//            {
//                try{
//                    carProfiles.add((CarProfile) inputFile.readObject());
//                    
//                }
//                catch (EOFException e)
//                {
//                    endOfFile = true;
//                }
//                catch(Exception f)
//                {
//                    JOptionPane.showMessageDialog(null, f.getMessage());
//                }
//            }
//            
//            inputFile.close();
//            
//        }
//        catch (IOException e)
//        {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }
//    
//    public void saveCarProfilestoFiles()
//    {
//        try
//        {
//            FileOutputStream file = new FileOutputStream("CarProfiles.dat");
//            ObjectOutputStream outputFile = new ObjectOutputStream(file);
//            
//            for (int i = 0; i< carProfiles.size(); i++)
//            {
//                outputFile.writeObject(carProfiles.get(i));
//            }
//            
//            outputFile.close();
//            JOptionPane.showMessageDialog(null, "Data saved successfully!!");
//            this.dispose();
//        }
//        catch (IOException e)
//        {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }
}
